### ISSUE TITLE
crypt15 WhatsApp Business Backup

### ISSUE THREAD

**Issue by warzonexd** [ElDavoo/wa-crypt-tools#67]
Can you explain to me how to decrypt crypt 15
I don't have the key

**Comment by ElDavoo** [comment]
You can't. It's not encryption if you can decrypt a message without a secret.

**Comment by joostvhts** [comment]
You would indeed need to acquire the key. Unfortunately, I have just been trying, and in my case it seems impossible: starting with Android 11+, the necessary folder is apparently no longer accessible to us, only to the app itself which cannot be used for `adb run-as` (it's not 'debuggable') which would otherwise have been able to help us get it.
